### PR TITLE
8 post comment

### PR DESCRIPTION
**Pull request by tomwvwest**

### CODE REVIEW

**Review by popatre — CHANGES_REQUESTED** [review]
- Lovely controlled components for the forms
- nice posting functionality to the api
- Lovely validation on the inputs

- [x] Please make the input a multitext area to allow for multi line inputs
- [x] We need a message to let the user know a post has failed. If i try and post whilst offline, I get no feedback to say it has failed - its says posted at the moment

**Review by nc-poppy-m — CHANGES_REQUESTED** [review]
A good bit closer! I can see you've implemented the feedback from last time. However, this still needs to be a bit clearer if the comment hasn't posted from a UI perspective
- Consider making a more visible indication (using colours etc) - it's quite hard to notice that little message in the corner and I actually missed it the first time. 
- If the comment hasn't posted, don't add it to the list

**Review by nc-modou — COMMENTED** [review]
Great response to feedback so far. Almost perfect & but one thing I noticed is that after an unsuccessful comment post, both 'error please try again' and 'posting...' are visible at the same time which is a bit confusing. Looks like you've got everything else in place

**Review by popatre — APPROVED** [review]
Much better - changes have been implemented well. Nice work! 🙌

**Pull request merged**
